[package]
name = "ragnarok"
version = "0.1.0"
authors = ["Gaute Hope <eg@gaute.vetsj.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web-view = { version = "*" }
hypocloid = { path = "../hypocloid" }

[dependencies.tokio]
features = ["full"]
version = "*"
